version: '3'
services:
 mongodb:
   image: mongo:3.3   
   expose:                 
     - "27017"
   volumes:
     - db_data:/data/db
   environment:    
    MONGODB_DATABASE: rsvpdata
   networks:
    - rsvpnet

 web:
   image: kardasa/rsvpapp:mooc
   ports:
    - "5000:5000"
   environment:
    MONGODB_HOST: mongodb
    LINK: http://www.kardasa.pl
    TEXT1: OpenAdmin.pl 
    TEXT2: Testowa Aplikacja!
    LOGO: http://www.kardasa.pl/uploads/images/CV/KardasA_Small.jpg
    COMPANY: Andrzej Kardaś OpenAdmin.pl
   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
